In [ ]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd

In [ ]:
with open("/content/drive/MyDrive/Messy_Sentiment_Data.html", 'r',encoding = "utf-8") as f:
  html_ = bs(f,'html.parser')
print(html_)
print(html_.prettify)

<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"/>
<title>Messy Sentiment Data Preview</title>
<style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f4f7f6;
        padding: 20px;
    }
    h2 {
        color: #2c3e50;
        text-align: center;
    }
    .mystyle {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        background-color: #ffffff;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    .mystyle thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
    }
    .mystyle th, .mystyle td {
        padding: 12px 15px;
        border: 1px solid #dddddd;
    }
    .mystyle tbody tr {
        border-bottom: 1px solid #dddddd;
    }
    .mystyle tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }
    .mystyle tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
    }
</style>
</head>
<body>
<h2>Messy Sentiment Analysis Dataset - Preview (First 50 Rows)</h2>
<p>This table contains the raw, messy data including typos, inconsistent naming, and formatting errors for cleaning practice.</p>
<table border="1" class="dataframe mystyle">
<thead>
<tr style="text-align: right;">
<th>Record_ID</th>
<th>Date</th>
<th>Month</th>
<th>Sector_Entity</th>
<th>Source_Platform</th>
<th>Sentiment</th>
<th>Sentiment_Score</th>
<th>Aspect_Category</th>
<th>Engagement_Volume</th>
<th>Impact_Weight</th>
</tr>
</thead>
<tbody>
<tr>
<td>REC-5000</td>
<td>2026-02-20 00:00:00</td>
<td>February</td>
<td>Banking Sector</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.71</td>
<td>Interest Rates</td>
<td>190,364</td>
<td>0.80</td>
</tr>
<tr>
<td>REC-5001</td>
<td>2026/31/02</td>
<td>March</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>-0.12</td>
<td>Project Timelines</td>
<td>185,924</td>
<td>0.53</td>
</tr>
<tr>
<td>REC-5002</td>
<td>2026-03-31 00:00:00</td>
<td>March</td>
<td>MEA</td>
<td>Twitter/X</td>
<td>Negative</td>
<td>-0.29</td>
<td>Diplomatic Relations</td>
<td>177,646</td>
<td>0.66</td>
</tr>
<tr>
<td>REC-5003</td>
<td>2026-02-23 00:00:00</td>
<td>February</td>
<td>MEA</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.64</td>
<td>Visa Services</td>
<td>6,029</td>
<td>0.70</td>
</tr>
<tr>
<td>REC-5004</td>
<td>2026-04-06 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>Twitter/X</td>
<td>Negative</td>
<td>-0.84</td>
<td>Crisis Management</td>
<td>241,698</td>
<td>0.54</td>
</tr>
<tr>
<td>REC-5005</td>
<td>2026-02-15 00:00:00</td>
<td>February</td>
<td>BANKING_SEC</td>
<td>YouTube</td>
<td>Positive</td>
<td>0.77</td>
<td>Customer Support</td>
<td>90,547</td>
<td>1.05</td>
</tr>
<tr>
<td>REC-5006</td>
<td>2026-04-01 00:00:00</td>
<td>April</td>
<td>MoRTH</td>
<td>YouTube</td>
<td>Neutral</td>
<td>0.07</td>
<td>Toll Management</td>
<td>114,403</td>
<td>1.31</td>
</tr>
<tr>
<td>REC-5007</td>
<td>2026-02-07 00:00:00</td>
<td>February</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Positive</td>
<td>0.20</td>
<td>Road Safety</td>
<td>194,275</td>
<td>1.18</td>
</tr>
<tr>
<td>REC-5008</td>
<td>2026-04-19 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>Twitter/X</td>
<td>Positive</td>
<td>0.82</td>
<td>Consular Services</td>
<td>123,915</td>
<td>1.46</td>
</tr>
<tr>
<td>REC-5009</td>
<td>2026-01-13 00:00:00</td>
<td>January</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.13</td>
<td>NaN</td>
<td>55,435</td>
<td>1.38</td>
</tr>
<tr>
<td>REC-5010</td>
<td>2026-03-17 00:00:00</td>
<td>March</td>
<td>Banking Sector</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.76</td>
<td>Cybersecurity</td>
<td>204,807</td>
<td>1.33</td>
</tr>
<tr>
<td>REC-5011</td>
<td>2026-04-16 00:00:00</td>
<td>April</td>
<td>Banking Sector</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>-0.11</td>
<td>Interest Rates</td>
<td>176,120</td>
<td>0.87</td>
</tr>
<tr>
<td>REC-5012</td>
<td>NaN</td>
<td>April</td>
<td>morth</td>
<td>NaN</td>
<td>Positive</td>
<td>0.71</td>
<td>Road Safety</td>
<td>5,963</td>
<td>1.38</td>
</tr>
<tr>
<td>REC-5013</td>
<td>2026/01/05</td>
<td>January</td>
<td>MEA</td>
<td>Reddit</td>
<td>Neutral</td>
<td>-0.19</td>
<td>International Trade</td>
<td>90,301</td>
<td>1.12</td>
</tr>
<tr>
<td>REC-5014</td>
<td>2026-04-02 00:00:00</td>
<td>April</td>
<td>MoRTH</td>
<td>News Portals</td>
<td>Neutral</td>
<td>0.16</td>
<td>Project Timelines</td>
<td>14,277</td>
<td>0.53</td>
</tr>
<tr>
<td>REC-5015</td>
<td>2026-04-13 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>News Portals</td>
<td>Neutral</td>
<td>-0.14</td>
<td>Consular Services</td>
<td>121,940</td>
<td>0.80</td>
</tr>
<tr>
<td>REC-5016</td>
<td>2026-04-22 00:00:00</td>
<td>April</td>
<td>BANKING_SEC</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>-0.04</td>
<td>Loan Processing</td>
<td>32,092</td>
<td>1.08</td>
</tr>
<tr>
<td>REC-5017</td>
<td>2026-01-22 00:00:00</td>
<td>January</td>
<td>Banking Sector</td>
<td>LinkedIn</td>
<td>Negative</td>
<td>-0.72</td>
<td>Customer Support</td>
<td>168,551</td>
<td>0.98</td>
</tr>
<tr>
<td>REC-5018</td>
<td>2026-03-24 00:00:00</td>
<td>March</td>
<td>External Affairs</td>
<td>News Portals</td>
<td>Negative</td>
<td>-0.63</td>
<td>Diplomatic Relations</td>
<td>167,693</td>
<td>1.43</td>
</tr>
<tr>
<td>REC-5019</td>
<td>2026-01-25 00:00:00</td>
<td>January</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.16</td>
<td>NaN</td>
<td>60,691</td>
<td>0.57</td>
</tr>
<tr>
<td>REC-5020</td>
<td>2026/03/07</td>
<td>March</td>
<td>M.E.A.</td>
<td>YouTube</td>
<td>Negative</td>
<td>-0.74</td>
<td>International Trade</td>
<td>188,402</td>
<td>0.57</td>
</tr>
<tr>
<td>REC-5021</td>
<td>2026/04/03</td>
<td>April</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.17</td>
<td>Visa Services</td>
<td>233,153</td>
<td>0.62</td>
</tr>
<tr>
<td>REC-5022</td>
<td>NaN</td>
<td>January</td>
<td>M.o.R.T.H</td>
<td>Reddit</td>
<td>Positive</td>
<td>0.90</td>
<td>Project Timelines</td>
<td>218,301</td>
<td>0.62</td>
</tr>
<tr>
<td>REC-5023</td>
<td>2026-01-29 00:00:00</td>
<td>January</td>
<td>ROAD_DEPT</td>
<td>LinkedIn</td>
<td>Neutral</td>
<td>-0.10</td>
<td>Toll Management</td>
<td>57,145</td>
<td>0.56</td>
</tr>
<tr>
<td>REC-5024</td>
<td>2026/02/27</td>
<td>February</td>
<td>MEA</td>
<td>YouTube</td>
<td>Negative</td>
<td>-0.83</td>
<td>Consular Services</td>
<td>243,808</td>
<td>1.09</td>
</tr>
<tr>
<td>REC-5025</td>
<td>2026-04-20 00:00:00</td>
<td>April</td>
<td>M.E.A.</td>
<td>Reddit</td>
<td>Neutral</td>
<td>999.00</td>
<td>Visa Services</td>
<td>101,440</td>
<td>0.56</td>
</tr>
<tr>
<td>REC-5026</td>
<td>2026-02-03 00:00:00</td>
<td>February</td>
<td>morth</td>
<td>LinkedIn</td>
<td>Neutral</td>
<td>-0.16</td>
<td>EV Infrastructure</td>
<td>161,450</td>
<td>0.69</td>
</tr>
<tr>
<td>REC-5027</td>
<td>2026-02-03 00:00:00</td>
<td>February</td>
<td>Banking Sector</td>
<td>Reddit</td>
<td>Negative</td>
<td>-0.38</td>
<td>Loan Processing</td>
<td>243,678</td>
<td>0.57</td>
</tr>
<tr>
<td>REC-5028</td>
<td>2026-03-24 00:00:00</td>
<td>March</td>
<td>morth</td>
<td>News Portals</td>
<td>Neutral</td>
<td>-0.09</td>
<td>Project Timelines</td>
<td>165,037</td>
<td>1.05</td>
</tr>
<tr>
<td>REC-5029</td>
<td>2026-04-05 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.01</td>
<td>NaN</td>
<td>181,580</td>
<td>1.04</td>
</tr>
<tr>
<td>REC-5030</td>
<td>2026-03-14 00:00:00</td>
<td>March</td>
<td>MoRTH</td>
<td>Reddit</td>
<td>Neutral</td>
<td>-0.18</td>
<td>Project Timelines</td>
<td>200,817</td>
<td>0.96</td>
</tr>
<tr>
<td>REC-5031</td>
<td>2026-02-09 00:00:00</td>
<td>February</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>0.10</td>
<td>Highway Infrastructure</td>
<td>89,925</td>
<td>0.87</td>
</tr>
<tr>
<td>REC-5032</td>
<td>2026-01-13 00:00:00</td>
<td>January</td>
<td>MoRTH</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.76</td>
<td>Highway Infrastructure</td>
<td>138,868</td>
<td>1.17</td>
</tr>
<tr>
<td>REC-5033</td>
<td>2026-03-16 00:00:00</td>
<td>March</td>
<td>MEA</td>
<td>LinkedIn</td>
<td>Positive</td>
<td>NaN</td>
<td>Crisis Management</td>
<td>229,186</td>
<td>0.94</td>
</tr>
<tr>
<td>REC-5034</td>
<td>2026-01-06 00:00:00</td>
<td>January</td>
<td>Banking Sector</td>
<td>LinkedIn</td>
<td>Negative</td>
<td>-0.38</td>
<td>Interest Rates</td>
<td>161,302</td>
<td>0.80</td>
</tr>
<tr>
<td>REC-5035</td>
<td>2026-01-08 00:00:00</td>
<td>January</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Positive</td>
<td>0.38</td>
<td>Toll Management</td>
<td>159,044</td>
<td>1.03</td>
</tr>
<tr>
<td>REC-5036</td>
<td>2026-03-05 00:00:00</td>
<td>March</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>0.09</td>
<td>EV Infrastructure</td>
<td>171,767</td>
<td>1.30</td>
</tr>
<tr>
<td>REC-5037</td>
<td>2026-01-09 00:00:00</td>
<td>January</td>
<td>MEA</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.76</td>
<td>International Trade</td>
<td>117,241</td>
<td>1.20</td>
</tr>
<tr>
<td>REC-5038</td>
<td>2026/31/02</td>
<td>April</td>
<td>BK-Sector</td>
<td>Twitter/X</td>
<td>Positive</td>
<td>0.96</td>
<td>Financial Results</td>
<td>138,249</td>
<td>1.10</td>
</tr>
<tr>
<td>REC-5039</td>
<td>2026/31/02</td>
<td>January</td>
<td>MEA</td>
<td>LinkedIn</td>
<td>Neutral</td>
<td>0.05</td>
<td>Visa Services</td>
<td>186,576</td>
<td>0.75</td>
</tr>
<tr>
<td>REC-5040</td>
<td>2026/03/24</td>
<td>March</td>
<td>Banking Sector</td>
<td>YouTube</td>
<td>Neutral</td>
<td>0.09</td>
<td>Customer Support</td>
<td>168,722</td>
<td>1.14</td>
</tr>
<tr>
<td>REC-5041</td>
<td>2026/31/02</td>
<td>February</td>
<td>Banking Sector</td>
<td>News Portals</td>
<td>Negative</td>
<td>-0.46</td>
<td>Cybersecurity</td>
<td>179,029</td>
<td>0.53</td>
</tr>
<tr>
<td>REC-5042</td>
<td>2026/31/02</td>
<td>April</td>
<td>ROAD_DEPT</td>
<td>Reddit</td>
<td>Neutral</td>
<td>0.01</td>
<td>Toll Management</td>
<td>129,688</td>
<td>0.97</td>
</tr>
<tr>
<td>REC-5043</td>
<td>2026-01-09 00:00:00</td>
<td>January</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Neutrl</td>
<td>-0.03</td>
<td>EV Infrastructure</td>
<td>198,624</td>
<td>0.64</td>
</tr>
<tr>
<td>REC-5044</td>
<td>2026-03-24 00:00:00</td>
<td>March</td>
<td>MoRTH</td>
<td>News Portals</td>
<td>Positve</td>
<td>0.75</td>
<td>Project Timelines</td>
<td>125,992</td>
<td>0.80</td>
</tr>
<tr>
<td>REC-5045</td>
<td>2026-01-10 00:00:00</td>
<td>January</td>
<td>MEA</td>
<td>LinkedIn</td>
<td>Positive</td>
<td>0.43</td>
<td>Diplomatic Relations</td>
<td>206,506</td>
<td>1.00</td>
</tr>
<tr>
<td>REC-5046</td>
<td>2026-04-23 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>0.09</td>
<td>Diplomatic Relations</td>
<td>188,206</td>
<td>0.52</td>
</tr>
<tr>
<td>REC-5047</td>
<td>2026-02-05 00:00:00</td>
<td>February</td>
<td>BANKING_SEC</td>
<td>NaN</td>
<td>Neutral</td>
<td>0.08</td>
<td>Interest Rates</td>
<td>27,783</td>
<td>1.09</td>
</tr>
<tr>
<td>REC-5048</td>
<td>2026-03-01 00:00:00</td>
<td>March</td>
<td>M.o.R.T.H</td>
<td>Reddit</td>
<td>Negatve</td>
<td>-0.27</td>
<td>Toll Management</td>
<td>118,278</td>
<td>1.34</td>
</tr>
<tr>
<td>REC-5049</td>
<td>2026-04-22 00:00:00</td>
<td>April</td>
<td>M.o.R.T.H</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>-0.06</td>
<td>Highway Infrastructure</td>
<td>130,795</td>
<td>1.13</td>
</tr>
</tbody>
</table>
</body>
</html>

<bound method Tag.prettify of
<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"/>
<title>Messy Sentiment Data Preview</title>
<style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f4f7f6;
        padding: 20px;
    }
    h2 {
        color: #2c3e50;
        text-align: center;
    }
    .mystyle {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        background-color: #ffffff;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    .mystyle thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
    }
    .mystyle th, .mystyle td {
        padding: 12px 15px;
        border: 1px solid #dddddd;
    }
    .mystyle tbody tr {
        border-bottom: 1px solid #dddddd;
    }
    .mystyle tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }
    .mystyle tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
    }
</style>
</head>
<body>
<h2>Messy Sentiment Analysis Dataset - Preview (First 50 Rows)</h2>
<p>This table contains the raw, messy data including typos, inconsistent naming, and formatting errors for cleaning practice.</p>
<table border="1" class="dataframe mystyle">
<thead>
<tr style="text-align: right;">
<th>Record_ID</th>
<th>Date</th>
<th>Month</th>
<th>Sector_Entity</th>
<th>Source_Platform</th>
<th>Sentiment</th>
<th>Sentiment_Score</th>
<th>Aspect_Category</th>
<th>Engagement_Volume</th>
<th>Impact_Weight</th>
</tr>
</thead>
<tbody>
<tr>
<td>REC-5000</td>
<td>2026-02-20 00:00:00</td>
<td>February</td>
<td>Banking Sector</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.71</td>
<td>Interest Rates</td>
<td>190,364</td>
<td>0.80</td>
</tr>
<tr>
<td>REC-5001</td>
<td>2026/31/02</td>
<td>March</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>-0.12</td>
<td>Project Timelines</td>
<td>185,924</td>
<td>0.53</td>
</tr>
<tr>
<td>REC-5002</td>
<td>2026-03-31 00:00:00</td>
<td>March</td>
<td>MEA</td>
<td>Twitter/X</td>
<td>Negative</td>
<td>-0.29</td>
<td>Diplomatic Relations</td>
<td>177,646</td>
<td>0.66</td>
</tr>
<tr>
<td>REC-5003</td>
<td>2026-02-23 00:00:00</td>
<td>February</td>
<td>MEA</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.64</td>
<td>Visa Services</td>
<td>6,029</td>
<td>0.70</td>
</tr>
<tr>
<td>REC-5004</td>
<td>2026-04-06 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>Twitter/X</td>
<td>Negative</td>
<td>-0.84</td>
<td>Crisis Management</td>
<td>241,698</td>
<td>0.54</td>
</tr>
<tr>
<td>REC-5005</td>
<td>2026-02-15 00:00:00</td>
<td>February</td>
<td>BANKING_SEC</td>
<td>YouTube</td>
<td>Positive</td>
<td>0.77</td>
<td>Customer Support</td>
<td>90,547</td>
<td>1.05</td>
</tr>
<tr>
<td>REC-5006</td>
<td>2026-04-01 00:00:00</td>
<td>April</td>
<td>MoRTH</td>
<td>YouTube</td>
<td>Neutral</td>
<td>0.07</td>
<td>Toll Management</td>
<td>114,403</td>
<td>1.31</td>
</tr>
<tr>
<td>REC-5007</td>
<td>2026-02-07 00:00:00</td>
<td>February</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Positive</td>
<td>0.20</td>
<td>Road Safety</td>
<td>194,275</td>
<td>1.18</td>
</tr>
<tr>
<td>REC-5008</td>
<td>2026-04-19 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>Twitter/X</td>
<td>Positive</td>
<td>0.82</td>
<td>Consular Services</td>
<td>123,915</td>
<td>1.46</td>
</tr>
<tr>
<td>REC-5009</td>
<td>2026-01-13 00:00:00</td>
<td>January</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.13</td>
<td>NaN</td>
<td>55,435</td>
<td>1.38</td>
</tr>
<tr>
<td>REC-5010</td>
<td>2026-03-17 00:00:00</td>
<td>March</td>
<td>Banking Sector</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.76</td>
<td>Cybersecurity</td>
<td>204,807</td>
<td>1.33</td>
</tr>
<tr>
<td>REC-5011</td>
<td>2026-04-16 00:00:00</td>
<td>April</td>
<td>Banking Sector</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>-0.11</td>
<td>Interest Rates</td>
<td>176,120</td>
<td>0.87</td>
</tr>
<tr>
<td>REC-5012</td>
<td>NaN</td>
<td>April</td>
<td>morth</td>
<td>NaN</td>
<td>Positive</td>
<td>0.71</td>
<td>Road Safety</td>
<td>5,963</td>
<td>1.38</td>
</tr>
<tr>
<td>REC-5013</td>
<td>2026/01/05</td>
<td>January</td>
<td>MEA</td>
<td>Reddit</td>
<td>Neutral</td>
<td>-0.19</td>
<td>International Trade</td>
<td>90,301</td>
<td>1.12</td>
</tr>
<tr>
<td>REC-5014</td>
<td>2026-04-02 00:00:00</td>
<td>April</td>
<td>MoRTH</td>
<td>News Portals</td>
<td>Neutral</td>
<td>0.16</td>
<td>Project Timelines</td>
<td>14,277</td>
<td>0.53</td>
</tr>
<tr>
<td>REC-5015</td>
<td>2026-04-13 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>News Portals</td>
<td>Neutral</td>
<td>-0.14</td>
<td>Consular Services</td>
<td>121,940</td>
<td>0.80</td>
</tr>
<tr>
<td>REC-5016</td>
<td>2026-04-22 00:00:00</td>
<td>April</td>
<td>BANKING_SEC</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>-0.04</td>
<td>Loan Processing</td>
<td>32,092</td>
<td>1.08</td>
</tr>
<tr>
<td>REC-5017</td>
<td>2026-01-22 00:00:00</td>
<td>January</td>
<td>Banking Sector</td>
<td>LinkedIn</td>
<td>Negative</td>
<td>-0.72</td>
<td>Customer Support</td>
<td>168,551</td>
<td>0.98</td>
</tr>
<tr>
<td>REC-5018</td>
<td>2026-03-24 00:00:00</td>
<td>March</td>
<td>External Affairs</td>
<td>News Portals</td>
<td>Negative</td>
<td>-0.63</td>
<td>Diplomatic Relations</td>
<td>167,693</td>
<td>1.43</td>
</tr>
<tr>
<td>REC-5019</td>
<td>2026-01-25 00:00:00</td>
<td>January</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.16</td>
<td>NaN</td>
<td>60,691</td>
<td>0.57</td>
</tr>
<tr>
<td>REC-5020</td>
<td>2026/03/07</td>
<td>March</td>
<td>M.E.A.</td>
<td>YouTube</td>
<td>Negative</td>
<td>-0.74</td>
<td>International Trade</td>
<td>188,402</td>
<td>0.57</td>
</tr>
<tr>
<td>REC-5021</td>
<td>2026/04/03</td>
<td>April</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.17</td>
<td>Visa Services</td>
<td>233,153</td>
<td>0.62</td>
</tr>
<tr>
<td>REC-5022</td>
<td>NaN</td>
<td>January</td>
<td>M.o.R.T.H</td>
<td>Reddit</td>
<td>Positive</td>
<td>0.90</td>
<td>Project Timelines</td>
<td>218,301</td>
<td>0.62</td>
</tr>
<tr>
<td>REC-5023</td>
<td>2026-01-29 00:00:00</td>
<td>January</td>
<td>ROAD_DEPT</td>
<td>LinkedIn</td>
<td>Neutral</td>
<td>-0.10</td>
<td>Toll Management</td>
<td>57,145</td>
<td>0.56</td>
</tr>
<tr>
<td>REC-5024</td>
<td>2026/02/27</td>
<td>February</td>
<td>MEA</td>
<td>YouTube</td>
<td>Negative</td>
<td>-0.83</td>
<td>Consular Services</td>
<td>243,808</td>
<td>1.09</td>
</tr>
<tr>
<td>REC-5025</td>
<td>2026-04-20 00:00:00</td>
<td>April</td>
<td>M.E.A.</td>
<td>Reddit</td>
<td>Neutral</td>
<td>999.00</td>
<td>Visa Services</td>
<td>101,440</td>
<td>0.56</td>
</tr>
<tr>
<td>REC-5026</td>
<td>2026-02-03 00:00:00</td>
<td>February</td>
<td>morth</td>
<td>LinkedIn</td>
<td>Neutral</td>
<td>-0.16</td>
<td>EV Infrastructure</td>
<td>161,450</td>
<td>0.69</td>
</tr>
<tr>
<td>REC-5027</td>
<td>2026-02-03 00:00:00</td>
<td>February</td>
<td>Banking Sector</td>
<td>Reddit</td>
<td>Negative</td>
<td>-0.38</td>
<td>Loan Processing</td>
<td>243,678</td>
<td>0.57</td>
</tr>
<tr>
<td>REC-5028</td>
<td>2026-03-24 00:00:00</td>
<td>March</td>
<td>morth</td>
<td>News Portals</td>
<td>Neutral</td>
<td>-0.09</td>
<td>Project Timelines</td>
<td>165,037</td>
<td>1.05</td>
</tr>
<tr>
<td>REC-5029</td>
<td>2026-04-05 00:00:00</td>
<td>April</td>
<td>MEA</td>
<td>YouTube</td>
<td>Neutral</td>
<td>-0.01</td>
<td>NaN</td>
<td>181,580</td>
<td>1.04</td>
</tr>
<tr>
<td>REC-5030</td>
<td>2026-03-14 00:00:00</td>
<td>March</td>
<td>MoRTH</td>
<td>Reddit</td>
<td>Neutral</td>
<td>-0.18</td>
<td>Project Timelines</td>
<td>200,817</td>
<td>0.96</td>
</tr>
<tr>
<td>REC-5031</td>
<td>2026-02-09 00:00:00</td>
<td>February</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Neutral</td>
<td>0.10</td>
<td>Highway Infrastructure</td>
<td>89,925</td>
<td>0.87</td>
</tr>
<tr>
<td>REC-5032</td>
<td>2026-01-13 00:00:00</td>
<td>January</td>
<td>MoRTH</td>
<td>News Portals</td>
<td>Positive</td>
<td>0.76</td>
<td>Highway Infrastructure</td>
<td>138,868</td>
<td>1.17</td>
</tr>
<tr>
<td>REC-5033</td>
<td>2026-03-16 00:00:00</td>
<td>March</td>
<td>MEA</td>
<td>LinkedIn</td>
<td>Positive</td>
<td>NaN</td>
<td>Crisis Management</td>
<td>229,186</td>
<td>0.94</td>
</tr>
<tr>
<td>REC-5034</td>
<td>2026-01-06 00:00:00</td>
<td>January</td>
<td>Banking Sector</td>
<td>LinkedIn</td>
<td>Negative</td>
<td>-0.38</td>
<td>Interest Rates</td>
<td>161,302</td>
<td>0.80</td>
</tr>
<tr>
<td>REC-5035</td>
<td>2026-01-08 00:00:00</td>
<td>January</td>
<td>MoRTH</td>
<td>Twitter/X</td>
<td>Positive</td>
<td>0.38</td>
<td>Toll Management</td>
<td>159,044</td>
<td>1.03</td>
</tr>
<tr>
<td>REC-5036</td>
<td>2026-03-05 00:00:00</td>
<td>March</td>
<td>MoRTH</td>

In [ ]:
headers_list = []
th = html_.find_all('th')
for i in th:
  headers_list.append(i.text)
print(headers_list)

['Record_ID', 'Date', 'Month', 'Sector_Entity', 'Source_Platform', 'Sentiment', 'Sentiment_Score', 'Aspect_Category', 'Engagement_Volume', 'Impact_Weight']

In [ ]:
data_list = []
tr = html_.find_all('tr')
for i in tr:
  td = i.find_all('td')
  row_data = [tds.get_text(strip = True) for tds in td]
  if row_data:
    data_list.append(row_data)
print(data_list)

[['REC-5000', '2026-02-20 00:00:00', 'February', 'Banking Sector', 'News Portals', 'Positive', '0.71', 'Interest Rates', '190,364', '0.80'], ['REC-5001', '2026/31/02', 'March', 'MoRTH', 'Twitter/X', 'Neutral', '-0.12', 'Project Timelines', '185,924', '0.53'], ['REC-5002', '2026-03-31 00:00:00', 'March', 'MEA', 'Twitter/X', 'Negative', '-0.29', 'Diplomatic Relations', '177,646', '0.66'], ['REC-5003', '2026-02-23 00:00:00', 'February', 'MEA', 'News Portals', 'Positive', '0.64', 'Visa Services', '6,029', '0.70'], ['REC-5004', '2026-04-06 00:00:00', 'April', 'MEA', 'Twitter/X', 'Negative', '-0.84', 'Crisis Management', '241,698', '0.54'], ['REC-5005', '2026-02-15 00:00:00', 'February', 'BANKING_SEC', 'YouTube', 'Positive', '0.77', 'Customer Support', '90,547', '1.05'], ['REC-5006', '2026-04-01 00:00:00', 'April', 'MoRTH', 'YouTube', 'Neutral', '0.07', 'Toll Management', '114,403', '1.31'], ['REC-5007', '2026-02-07 00:00:00', 'February', 'MoRTH', 'Twitter/X', 'Positive', '0.20', 'Road Safety', '194,275', '1.18'], ['REC-5008', '2026-04-19 00:00:00', 'April', 'MEA', 'Twitter/X', 'Positive', '0.82', 'Consular Services', '123,915', '1.46'], ['REC-5009', '2026-01-13 00:00:00', 'January', 'MEA', 'YouTube', 'Neutral', '-0.13', 'NaN', '55,435', '1.38'], ['REC-5010', '2026-03-17 00:00:00', 'March', 'Banking Sector', 'News Portals', 'Positive', '0.76', 'Cybersecurity', '204,807', '1.33'], ['REC-5011', '2026-04-16 00:00:00', 'April', 'Banking Sector', 'Twitter/X', 'Neutral', '-0.11', 'Interest Rates', '176,120', '0.87'], ['REC-5012', 'NaN', 'April', 'morth', 'NaN', 'Positive', '0.71', 'Road Safety', '5,963', '1.38'], ['REC-5013', '2026/01/05', 'January', 'MEA', 'Reddit', 'Neutral', '-0.19', 'International Trade', '90,301', '1.12'], ['REC-5014', '2026-04-02 00:00:00', 'April', 'MoRTH', 'News Portals', 'Neutral', '0.16', 'Project Timelines', '14,277', '0.53'], ['REC-5015', '2026-04-13 00:00:00', 'April', 'MEA', 'News Portals', 'Neutral', '-0.14', 'Consular Services', '121,940', '0.80'], ['REC-5016', '2026-04-22 00:00:00', 'April', 'BANKING_SEC', 'Twitter/X', 'Neutral', '-0.04', 'Loan Processing', '32,092', '1.08'], ['REC-5017', '2026-01-22 00:00:00', 'January', 'Banking Sector', 'LinkedIn', 'Negative', '-0.72', 'Customer Support', '168,551', '0.98'], ['REC-5018', '2026-03-24 00:00:00', 'March', 'External Affairs', 'News Portals', 'Negative', '-0.63', 'Diplomatic Relations', '167,693', '1.43'], ['REC-5019', '2026-01-25 00:00:00', 'January', 'MEA', 'YouTube', 'Neutral', '-0.16', 'NaN', '60,691', '0.57'], ['REC-5020', '2026/03/07', 'March', 'M.E.A.', 'YouTube', 'Negative', '-0.74', 'International Trade', '188,402', '0.57'], ['REC-5021', '2026/04/03', 'April', 'MEA', 'YouTube', 'Neutral', '-0.17', 'Visa Services', '233,153', '0.62'], ['REC-5022', 'NaN', 'January', 'M.o.R.T.H', 'Reddit', 'Positive', '0.90', 'Project Timelines', '218,301', '0.62'], ['REC-5023', '2026-01-29 00:00:00', 'January', 'ROAD_DEPT', 'LinkedIn', 'Neutral', '-0.10', 'Toll Management', '57,145', '0.56'], ['REC-5024', '2026/02/27', 'February', 'MEA', 'YouTube', 'Negative', '-0.83', 'Consular Services', '243,808', '1.09'], ['REC-5025', '2026-04-20 00:00:00', 'April', 'M.E.A.', 'Reddit', 'Neutral', '999.00', 'Visa Services', '101,440', '0.56'], ['REC-5026', '2026-02-03 00:00:00', 'February', 'morth', 'LinkedIn', 'Neutral', '-0.16', 'EV Infrastructure', '161,450', '0.69'], ['REC-5027', '2026-02-03 00:00:00', 'February', 'Banking Sector', 'Reddit', 'Negative', '-0.38', 'Loan Processing', '243,678', '0.57'], ['REC-5028', '2026-03-24 00:00:00', 'March', 'morth', 'News Portals', 'Neutral', '-0.09', 'Project Timelines', '165,037', '1.05'], ['REC-5029', '2026-04-05 00:00:00', 'April', 'MEA', 'YouTube', 'Neutral', '-0.01', 'NaN', '181,580', '1.04'], ['REC-5030', '2026-03-14 00:00:00', 'March', 'MoRTH', 'Reddit', 'Neutral', '-0.18', 'Project Timelines', '200,817', '0.96'], ['REC-5031', '2026-02-09 00:00:00', 'February', 'MoRTH', 'Twitter/X', 'Neutral', '0.10', 'Highway Infrastructure', '89,925', '0.87'], ['REC-5032', '2026-01-13 00:00:00', 'January', 'MoRTH', 'News Portals', 'Positive', '0.76', 'Highway Infrastructure', '138,868', '1.17'], ['REC-5033', '2026-03-16 00:00:00', 'March', 'MEA', 'LinkedIn', 'Positive', 'NaN', 'Crisis Management', '229,186', '0.94'], ['REC-5034', '2026-01-06 00:00:00', 'January', 'Banking Sector', 'LinkedIn', 'Negative', '-0.38', 'Interest Rates', '161,302', '0.80'], ['REC-5035', '2026-01-08 00:00:00', 'January', 'MoRTH', 'Twitter/X', 'Positive', '0.38', 'Toll Management', '159,044', '1.03'], ['REC-5036', '2026-03-05 00:00:00', 'March', 'MoRTH', 'Twitter/X', 'Neutral', '0.09', 'EV Infrastructure', '171,767', '1.30'], ['REC-5037', '2026-01-09 00:00:00', 'January', 'MEA', 'News Portals', 'Positive', '0.76', 'International Trade', '117,241', '1.20'], ['REC-5038', '2026/31/02', 'April', 'BK-Sector', 'Twitter/X', 'Positive', '0.96', 'Financial Results', '138,249', '1.10'], ['REC-5039', '2026/31/02', 'January', 'MEA', 'LinkedIn', 'Neutral', '0.05', 'Visa Services', '186,576', '0.75'], ['REC-5040', '2026/03/24', 'March', 'Banking Sector', 'YouTube', 'Neutral', '0.09', 'Customer Support', '168,722', '1.14'], ['REC-5041', '2026/31/02', 'February', 'Banking Sector', 'News Portals', 'Negative', '-0.46', 'Cybersecurity', '179,029', '0.53'], ['REC-5042', '2026/31/02', 'April', 'ROAD_DEPT', 'Reddit', 'Neutral', '0.01', 'Toll Management', '129,688', '0.97'], ['REC-5043', '2026-01-09 00:00:00', 'January', 'MoRTH', 'Twitter/X', 'Neutrl', '-0.03', 'EV Infrastructure', '198,624', '0.64'], ['REC-5044', '2026-03-24 00:00:00', 'March', 'MoRTH', 'News Portals', 'Positve', '0.75', 'Project Timelines', '125,992', '0.80'], ['REC-5045', '2026-01-10 00:00:00', 'January', 'MEA', 'LinkedIn', 'Positive', '0.43', 'Diplomatic Relations', '206,506', '1.00'], ['REC-5046', '2026-04-23 00:00:00', 'April', 'MEA', 'Twitter/X', 'Neutral', '0.09', 'Diplomatic Relations', '188,206', '0.52'], ['REC-5047', '2026-02-05 00:00:00', 'February', 'BANKING_SEC', 'NaN', 'Neutral', '0.08', 'Interest Rates', '27,783', '1.09'], ['REC-5048', '2026-03-01 00:00:00', 'March', 'M.o.R.T.H', 'Reddit', 'Negatve', '-0.27', 'Toll Management', '118,278', '1.34'], ['REC-5049', '2026-04-22 00:00:00', 'April', 'M.o.R.T.H', 'Twitter/X', 'Neutral', '-0.06', 'Highway Infrastructure', '130,795', '1.13']]

In [ ]:
Client_Progress_dataset = [dict(zip(headers_list,row)) for row in data_list]
print(Client_Progress_dataset)

[{'Record_ID': 'REC-5000', 'Date': '2026-02-20 00:00:00', 'Month': 'February', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'News Portals', 'Sentiment': 'Positive', 'Sentiment_Score': '0.71', 'Aspect_Category': 'Interest Rates', 'Engagement_Volume': '190,364', 'Impact_Weight': '0.80'}, {'Record_ID': 'REC-5001', 'Date': '2026/31/02', 'Month': 'March', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.12', 'Aspect_Category': 'Project Timelines', 'Engagement_Volume': '185,924', 'Impact_Weight': '0.53'}, {'Record_ID': 'REC-5002', 'Date': '2026-03-31 00:00:00', 'Month': 'March', 'Sector_Entity': 'MEA', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.29', 'Aspect_Category': 'Diplomatic Relations', 'Engagement_Volume': '177,646', 'Impact_Weight': '0.66'}, {'Record_ID': 'REC-5003', 'Date': '2026-02-23 00:00:00', 'Month': 'February', 'Sector_Entity': 'MEA', 'Source_Platform': 'News Portals', 'Sentiment': 'Positive', 'Sentiment_Score': '0.64', 'Aspect_Category': 'Visa Services', 'Engagement_Volume': '6,029', 'Impact_Weight': '0.70'}, {'Record_ID': 'REC-5004', 'Date': '2026-04-06 00:00:00', 'Month': 'April', 'Sector_Entity': 'MEA', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.84', 'Aspect_Category': 'Crisis Management', 'Engagement_Volume': '241,698', 'Impact_Weight': '0.54'}, {'Record_ID': 'REC-5005', 'Date': '2026-02-15 00:00:00', 'Month': 'February', 'Sector_Entity': 'BANKING_SEC', 'Source_Platform': 'YouTube', 'Sentiment': 'Positive', 'Sentiment_Score': '0.77', 'Aspect_Category': 'Customer Support', 'Engagement_Volume': '90,547', 'Impact_Weight': '1.05'}, {'Record_ID': 'REC-5006', 'Date': '2026-04-01 00:00:00', 'Month': 'April', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'YouTube', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.07', 'Aspect_Category': 'Toll Management', 'Engagement_Volume': '114,403', 'Impact_Weight': '1.31'}, {'Record_ID': 'REC-5007', 'Date': '2026-02-07 00:00:00', 'Month': 'February', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Positive', 'Sentiment_Score': '0.20', 'Aspect_Category': 'Road Safety', 'Engagement_Volume': '194,275', 'Impact_Weight': '1.18'}, {'Record_ID': 'REC-5008', 'Date': '2026-04-19 00:00:00', 'Month': 'April', 'Sector_Entity': 'MEA', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Positive', 'Sentiment_Score': '0.82', 'Aspect_Category': 'Consular Services', 'Engagement_Volume': '123,915', 'Impact_Weight': '1.46'}, {'Record_ID': 'REC-5009', 'Date': '2026-01-13 00:00:00', 'Month': 'January', 'Sector_Entity': 'MEA', 'Source_Platform': 'YouTube', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.13', 'Aspect_Category': 'NaN', 'Engagement_Volume': '55,435', 'Impact_Weight': '1.38'}, {'Record_ID': 'REC-5010', 'Date': '2026-03-17 00:00:00', 'Month': 'March', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'News Portals', 'Sentiment': 'Positive', 'Sentiment_Score': '0.76', 'Aspect_Category': 'Cybersecurity', 'Engagement_Volume': '204,807', 'Impact_Weight': '1.33'}, {'Record_ID': 'REC-5011', 'Date': '2026-04-16 00:00:00', 'Month': 'April', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.11', 'Aspect_Category': 'Interest Rates', 'Engagement_Volume': '176,120', 'Impact_Weight': '0.87'}, {'Record_ID': 'REC-5012', 'Date': 'NaN', 'Month': 'April', 'Sector_Entity': 'morth', 'Source_Platform': 'NaN', 'Sentiment': 'Positive', 'Sentiment_Score': '0.71', 'Aspect_Category': 'Road Safety', 'Engagement_Volume': '5,963', 'Impact_Weight': '1.38'}, {'Record_ID': 'REC-5013', 'Date': '2026/01/05', 'Month': 'January', 'Sector_Entity': 'MEA', 'Source_Platform': 'Reddit', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.19', 'Aspect_Category': 'International Trade', 'Engagement_Volume': '90,301', 'Impact_Weight': '1.12'}, {'Record_ID': 'REC-5014', 'Date': '2026-04-02 00:00:00', 'Month': 'April', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'News Portals', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.16', 'Aspect_Category': 'Project Timelines', 'Engagement_Volume': '14,277', 'Impact_Weight': '0.53'}, {'Record_ID': 'REC-5015', 'Date': '2026-04-13 00:00:00', 'Month': 'April', 'Sector_Entity': 'MEA', 'Source_Platform': 'News Portals', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.14', 'Aspect_Category': 'Consular Services', 'Engagement_Volume': '121,940', 'Impact_Weight': '0.80'}, {'Record_ID': 'REC-5016', 'Date': '2026-04-22 00:00:00', 'Month': 'April', 'Sector_Entity': 'BANKING_SEC', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.04', 'Aspect_Category': 'Loan Processing', 'Engagement_Volume': '32,092', 'Impact_Weight': '1.08'}, {'Record_ID': 'REC-5017', 'Date': '2026-01-22 00:00:00', 'Month': 'January', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'LinkedIn', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.72', 'Aspect_Category': 'Customer Support', 'Engagement_Volume': '168,551', 'Impact_Weight': '0.98'}, {'Record_ID': 'REC-5018', 'Date': '2026-03-24 00:00:00', 'Month': 'March', 'Sector_Entity': 'External Affairs', 'Source_Platform': 'News Portals', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.63', 'Aspect_Category': 'Diplomatic Relations', 'Engagement_Volume': '167,693', 'Impact_Weight': '1.43'}, {'Record_ID': 'REC-5019', 'Date': '2026-01-25 00:00:00', 'Month': 'January', 'Sector_Entity': 'MEA', 'Source_Platform': 'YouTube', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.16', 'Aspect_Category': 'NaN', 'Engagement_Volume': '60,691', 'Impact_Weight': '0.57'}, {'Record_ID': 'REC-5020', 'Date': '2026/03/07', 'Month': 'March', 'Sector_Entity': 'M.E.A.', 'Source_Platform': 'YouTube', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.74', 'Aspect_Category': 'International Trade', 'Engagement_Volume': '188,402', 'Impact_Weight': '0.57'}, {'Record_ID': 'REC-5021', 'Date': '2026/04/03', 'Month': 'April', 'Sector_Entity': 'MEA', 'Source_Platform': 'YouTube', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.17', 'Aspect_Category': 'Visa Services', 'Engagement_Volume': '233,153', 'Impact_Weight': '0.62'}, {'Record_ID': 'REC-5022', 'Date': 'NaN', 'Month': 'January', 'Sector_Entity': 'M.o.R.T.H', 'Source_Platform': 'Reddit', 'Sentiment': 'Positive', 'Sentiment_Score': '0.90', 'Aspect_Category': 'Project Timelines', 'Engagement_Volume': '218,301', 'Impact_Weight': '0.62'}, {'Record_ID': 'REC-5023', 'Date': '2026-01-29 00:00:00', 'Month': 'January', 'Sector_Entity': 'ROAD_DEPT', 'Source_Platform': 'LinkedIn', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.10', 'Aspect_Category': 'Toll Management', 'Engagement_Volume': '57,145', 'Impact_Weight': '0.56'}, {'Record_ID': 'REC-5024', 'Date': '2026/02/27', 'Month': 'February', 'Sector_Entity': 'MEA', 'Source_Platform': 'YouTube', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.83', 'Aspect_Category': 'Consular Services', 'Engagement_Volume': '243,808', 'Impact_Weight': '1.09'}, {'Record_ID': 'REC-5025', 'Date': '2026-04-20 00:00:00', 'Month': 'April', 'Sector_Entity': 'M.E.A.', 'Source_Platform': 'Reddit', 'Sentiment': 'Neutral', 'Sentiment_Score': '999.00', 'Aspect_Category': 'Visa Services', 'Engagement_Volume': '101,440', 'Impact_Weight': '0.56'}, {'Record_ID': 'REC-5026', 'Date': '2026-02-03 00:00:00', 'Month': 'February', 'Sector_Entity': 'morth', 'Source_Platform': 'LinkedIn', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.16', 'Aspect_Category': 'EV Infrastructure', 'Engagement_Volume': '161,450', 'Impact_Weight': '0.69'}, {'Record_ID': 'REC-5027', 'Date': '2026-02-03 00:00:00', 'Month': 'February', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'Reddit', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.38', 'Aspect_Category': 'Loan Processing', 'Engagement_Volume': '243,678', 'Impact_Weight': '0.57'}, {'Record_ID': 'REC-5028', 'Date': '2026-03-24 00:00:00', 'Month': 'March', 'Sector_Entity': 'morth', 'Source_Platform': 'News Portals', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.09', 'Aspect_Category': 'Project Timelines', 'Engagement_Volume': '165,037', 'Impact_Weight': '1.05'}, {'Record_ID': 'REC-5029', 'Date': '2026-04-05 00:00:00', 'Month': 'April', 'Sector_Entity': 'MEA', 'Source_Platform': 'YouTube', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.01', 'Aspect_Category': 'NaN', 'Engagement_Volume': '181,580', 'Impact_Weight': '1.04'}, {'Record_ID': 'REC-5030', 'Date': '2026-03-14 00:00:00', 'Month': 'March', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'Reddit', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.18', 'Aspect_Category': 'Project Timelines', 'Engagement_Volume': '200,817', 'Impact_Weight': '0.96'}, {'Record_ID': 'REC-5031', 'Date': '2026-02-09 00:00:00', 'Month': 'February', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.10', 'Aspect_Category': 'Highway Infrastructure', 'Engagement_Volume': '89,925', 'Impact_Weight': '0.87'}, {'Record_ID': 'REC-5032', 'Date': '2026-01-13 00:00:00', 'Month': 'January', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'News Portals', 'Sentiment': 'Positive', 'Sentiment_Score': '0.76', 'Aspect_Category': 'Highway Infrastructure', 'Engagement_Volume': '138,868', 'Impact_Weight': '1.17'}, {'Record_ID': 'REC-5033', 'Date': '2026-03-16 00:00:00', 'Month': 'March', 'Sector_Entity': 'MEA', 'Source_Platform': 'LinkedIn', 'Sentiment': 'Positive', 'Sentiment_Score': 'NaN', 'Aspect_Category': 'Crisis Management', 'Engagement_Volume': '229,186', 'Impact_Weight': '0.94'}, {'Record_ID': 'REC-5034', 'Date': '2026-01-06 00:00:00', 'Month': 'January', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'LinkedIn', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.38', 'Aspect_Category': 'Interest Rates', 'Engagement_Volume': '161,302', 'Impact_Weight': '0.80'}, {'Record_ID': 'REC-5035', 'Date': '2026-01-08 00:00:00', 'Month': 'January', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Positive', 'Sentiment_Score': '0.38', 'Aspect_Category': 'Toll Management', 'Engagement_Volume': '159,044', 'Impact_Weight': '1.03'}, {'Record_ID': 'REC-5036', 'Date': '2026-03-05 00:00:00', 'Month': 'March', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.09', 'Aspect_Category': 'EV Infrastructure', 'Engagement_Volume': '171,767', 'Impact_Weight': '1.30'}, {'Record_ID': 'REC-5037', 'Date': '2026-01-09 00:00:00', 'Month': 'January', 'Sector_Entity': 'MEA', 'Source_Platform': 'News Portals', 'Sentiment': 'Positive', 'Sentiment_Score': '0.76', 'Aspect_Category': 'International Trade', 'Engagement_Volume': '117,241', 'Impact_Weight': '1.20'}, {'Record_ID': 'REC-5038', 'Date': '2026/31/02', 'Month': 'April', 'Sector_Entity': 'BK-Sector', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Positive', 'Sentiment_Score': '0.96', 'Aspect_Category': 'Financial Results', 'Engagement_Volume': '138,249', 'Impact_Weight': '1.10'}, {'Record_ID': 'REC-5039', 'Date': '2026/31/02', 'Month': 'January', 'Sector_Entity': 'MEA', 'Source_Platform': 'LinkedIn', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.05', 'Aspect_Category': 'Visa Services', 'Engagement_Volume': '186,576', 'Impact_Weight': '0.75'}, {'Record_ID': 'REC-5040', 'Date': '2026/03/24', 'Month': 'March', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'YouTube', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.09', 'Aspect_Category': 'Customer Support', 'Engagement_Volume': '168,722', 'Impact_Weight': '1.14'}, {'Record_ID': 'REC-5041', 'Date': '2026/31/02', 'Month': 'February', 'Sector_Entity': 'Banking Sector', 'Source_Platform': 'News Portals', 'Sentiment': 'Negative', 'Sentiment_Score': '-0.46', 'Aspect_Category': 'Cybersecurity', 'Engagement_Volume': '179,029', 'Impact_Weight': '0.53'}, {'Record_ID': 'REC-5042', 'Date': '2026/31/02', 'Month': 'April', 'Sector_Entity': 'ROAD_DEPT', 'Source_Platform': 'Reddit', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.01', 'Aspect_Category': 'Toll Management', 'Engagement_Volume': '129,688', 'Impact_Weight': '0.97'}, {'Record_ID': 'REC-5043', 'Date': '2026-01-09 00:00:00', 'Month': 'January', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutrl', 'Sentiment_Score': '-0.03', 'Aspect_Category': 'EV Infrastructure', 'Engagement_Volume': '198,624', 'Impact_Weight': '0.64'}, {'Record_ID': 'REC-5044', 'Date': '2026-03-24 00:00:00', 'Month': 'March', 'Sector_Entity': 'MoRTH', 'Source_Platform': 'News Portals', 'Sentiment': 'Positve', 'Sentiment_Score': '0.75', 'Aspect_Category': 'Project Timelines', 'Engagement_Volume': '125,992', 'Impact_Weight': '0.80'}, {'Record_ID': 'REC-5045', 'Date': '2026-01-10 00:00:00', 'Month': 'January', 'Sector_Entity': 'MEA', 'Source_Platform': 'LinkedIn', 'Sentiment': 'Positive', 'Sentiment_Score': '0.43', 'Aspect_Category': 'Diplomatic Relations', 'Engagement_Volume': '206,506', 'Impact_Weight': '1.00'}, {'Record_ID': 'REC-5046', 'Date': '2026-04-23 00:00:00', 'Month': 'April', 'Sector_Entity': 'MEA', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.09', 'Aspect_Category': 'Diplomatic Relations', 'Engagement_Volume': '188,206', 'Impact_Weight': '0.52'}, {'Record_ID': 'REC-5047', 'Date': '2026-02-05 00:00:00', 'Month': 'February', 'Sector_Entity': 'BANKING_SEC', 'Source_Platform': 'NaN', 'Sentiment': 'Neutral', 'Sentiment_Score': '0.08', 'Aspect_Category': 'Interest Rates', 'Engagement_Volume': '27,783', 'Impact_Weight': '1.09'}, {'Record_ID': 'REC-5048', 'Date': '2026-03-01 00:00:00', 'Month': 'March', 'Sector_Entity': 'M.o.R.T.H', 'Source_Platform': 'Reddit', 'Sentiment': 'Negatve', 'Sentiment_Score': '-0.27', 'Aspect_Category': 'Toll Management', 'Engagement_Volume': '118,278', 'Impact_Weight': '1.34'}, {'Record_ID': 'REC-5049', 'Date': '2026-04-22 00:00:00', 'Month': 'April', 'Sector_Entity': 'M.o.R.T.H', 'Source_Platform': 'Twitter/X', 'Sentiment': 'Neutral', 'Sentiment_Score': '-0.06', 'Aspect_Category': 'Highway Infrastructure', 'Engagement_Volume': '130,795', 'Impact_Weight': '1.13'}]

In [ ]:
client_Progress_dataset = pd.DataFrame(Client_Progress_dataset)

In [ ]:
client_Progress_dataset.to_csv('Client_Progress_dataset_Scrap.csv')